default:
	@just --list

NAME := "{{cookiecutter.project_slug}}"
VERSION := "0.1"
GIT_COMMIT := `git rev-parse HEAD`
BUILD_TIME := `date '+%Y-%m-%d-%H:%M:%S'`
LDFLAGS := "-X github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/version.Name="+NAME+"
            -X github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/version.Version="+VERSION+"
            -X github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/version.GitCommit="+GIT_COMMIT+"
            -X github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/version.BuildTime="+BUILD_TIME+"
           "

run:
	go run -ldflags '{{ "{{LDFLAGS}}" }}' main.go

build:
	go build -ldflags '{{ "{{LDFLAGS}}" }}'

install-static:
	go install -ldflags '-w -linkmode external -extldflags "-static" {{ "{{LDFLAGS}}" }}'

package:
	docker build -t {{cookiecutter.docker_hub_username}}/{{cookiecutter.project_slug}}:{{ "{{VERSION}}" }} .
